# Generated by Django 4.2.6 on 2023-10-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(upload_to="", verbose_name="Profil picture"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("CREATOR", "Creator"), ("SUBSCRIBER", "Subscriber")],
                max_length=20,
                verbose_name="Role",
            ),
        ),
    ]
